server:
  port: 8000

spring:
  application:
    name: gateway-template
  cloud:
    consul:
      host: consul-server.consul.svc.cluster.local
      port: 8500
      discovery:
        prefer-ip-address: true
        instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    gateway:
      httpclient:
        connect-timeout: 2
        response-timeout: 2s
      globalcors:
        cors-configurations:
          "[/**]":
            allowedOrigins: "*"
            allowedMethods: "*"
      discovery:
        locator:
          enabled: true

logging:
  level:
    org.springframework.cloud.gateway: debug
    org.springframework.http.server.reactive: debug
    org.springframework.web.reactive: debug
    org.springframework.boot.autoconfigure.web: debug
