/*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.17.0).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.sct.demo.client.config;

import com.sct.demo.client.api.DemoControllerApi;

import org.springframework.context.annotation.Bean;
import org.springframework.web.reactive.function.client.WebClient;
import org.springframework.web.reactive.function.client.support.WebClientAdapter;
import org.springframework.web.service.invoker.HttpServiceProxyFactory;

public abstract class HttpInterfacesAbstractConfigurator {

    private final WebClient webClient;

    public HttpInterfacesAbstractConfigurator(final WebClient webClient) {
        this.webClient = webClient;
    }

    @Bean(name = "com.sct.demo.client.config.HttpInterfacesAbstractConfigurator.demoController")
    DemoControllerApi demoControllerHttpProxy() {
        HttpServiceProxyFactory factory = HttpServiceProxyFactory.builderFor(WebClientAdapter.create(webClient)).build();
        return factory.createClient(DemoControllerApi.class);
    }


}
