server:
  port: 8080

spring:
  application:
    name: service-template
  cloud:
    consul:
      host: consul-server.consul.svc.cluster.local
      port: 8500
      discovery:
        prefer-ip-address: true
        instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
  web:
    resources:
      add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true
    log-request-details: true

logging:
  level:
    org.springframework.web: debug
