server:
  port: 8080

spring:
  application:
    name: service-template
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        prefer-ip-address: true
        instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
  mvc:
    log-request-details: true

logging:
  level:
    org.springframework.web: debug
