/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.17.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.sct.system.client.api;

import com.sct.system.client.model.DeptBasicDto;
import com.sct.system.client.model.DeptDto;
import com.sct.system.client.model.DeptQueryDto;
import org.springframework.lang.Nullable;
import com.sct.system.client.model.PageResponseDtoDeptDto;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.service.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;


@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-12-10T10:12:59.932325+08:00[Asia/Shanghai]", comments = "Generator version: 7.17.0")
public interface DeptControllerApi {

    /**
     * GET /dept/count
     *
     * @param dto  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "GET",
        value = "/dept/count",
        accept = { "*/*" }
    )
    ResponseEntity<Long> countAllDeptBy(
        @Parameter(name = "dto", description = "", required = true, in = ParameterIn.QUERY) DeptQueryDto dto
    );


    /**
     * POST /dept
     *
     * @param deptDto  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "POST",
        value = "/dept",
        accept = { "application/json" },
        contentType = "application/json"
    )
    ResponseEntity<Void> createDept(
        @Parameter(name = "DeptDto", description = "", required = true) @RequestBody DeptDto deptDto
    );


    /**
     * DELETE /dept/{id}
     *
     * @param id  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "DELETE",
        value = "/dept/{id}",
        accept = { "application/json" }
    )
    ResponseEntity<Void> deleteDeptById(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Long id
    );


    /**
     * GET /dept/basic
     *
     * @param dto  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "GET",
        value = "/dept/basic",
        accept = { "*/*" }
    )
    ResponseEntity<List<DeptBasicDto>> findAllDeptBasicBy(
        @Parameter(name = "dto", description = "", required = true, in = ParameterIn.QUERY) DeptQueryDto dto
    );


    /**
     * GET /dept
     *
     * @param dto  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "GET",
        value = "/dept",
        accept = { "*/*" }
    )
    ResponseEntity<List<DeptDto>> findAllDeptBy(
        @Parameter(name = "dto", description = "", required = true, in = ParameterIn.QUERY) DeptQueryDto dto
    );


    /**
     * GET /dept/page
     *
     * @param queryDto  (required)
     * @param pageNum  (optional, default to 1)
     * @param pageSize  (optional, default to 10)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "GET",
        value = "/dept/page",
        accept = { "*/*" }
    )
    ResponseEntity<PageResponseDtoDeptDto> findAllDeptPageBy(
        @Parameter(name = "queryDto", description = "", required = true, in = ParameterIn.QUERY) DeptQueryDto queryDto,
        @Parameter(name = "pageNum", description = "", in = ParameterIn.QUERY) @RequestParam(value = "pageNum", required = false, defaultValue = "1") Integer pageNum,
        @Parameter(name = "pageSize", description = "", in = ParameterIn.QUERY) @RequestParam(value = "pageSize", required = false, defaultValue = "10") Integer pageSize
    );


    /**
     * GET /dept/{id}
     *
     * @param id  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "GET",
        value = "/dept/{id}",
        accept = { "*/*" }
    )
    ResponseEntity<DeptDto> findDeptById(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Long id
    );


    /**
     * PUT /dept/{id}
     *
     * @param id  (required)
     * @param deptDto  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "PUT",
        value = "/dept/{id}",
        accept = { "application/json" },
        contentType = "application/json"
    )
    ResponseEntity<Void> updateDeptById(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Long id,
        @Parameter(name = "DeptDto", description = "", required = true) @RequestBody DeptDto deptDto
    );

}
