/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.17.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.sct.system.client.api;

import com.sct.system.client.model.DictTypeBasicDto;
import com.sct.system.client.model.DictTypeDto;
import com.sct.system.client.model.DictTypeQueryDto;
import org.springframework.lang.Nullable;
import com.sct.system.client.model.PageResponseDtoDictTypeDto;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.service.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;


@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-12-10T10:12:59.932325+08:00[Asia/Shanghai]", comments = "Generator version: 7.17.0")
public interface DictTypeControllerApi {

    /**
     * GET /dict-type/count
     *
     * @param dto  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "GET",
        value = "/dict-type/count",
        accept = { "*/*" }
    )
    ResponseEntity<Long> countAllDictTypeBy(
        @Parameter(name = "dto", description = "", required = true, in = ParameterIn.QUERY) DictTypeQueryDto dto
    );


    /**
     * POST /dict-type
     *
     * @param dictTypeDto  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "POST",
        value = "/dict-type",
        accept = { "application/json" },
        contentType = "application/json"
    )
    ResponseEntity<Void> createDictType(
        @Parameter(name = "DictTypeDto", description = "", required = true) @RequestBody DictTypeDto dictTypeDto
    );


    /**
     * DELETE /dict-type/{id}
     *
     * @param id  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "DELETE",
        value = "/dict-type/{id}",
        accept = { "application/json" }
    )
    ResponseEntity<Void> deleteDictTypeById(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Long id
    );


    /**
     * GET /dict-type/basic
     *
     * @param dto  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "GET",
        value = "/dict-type/basic",
        accept = { "*/*" }
    )
    ResponseEntity<List<DictTypeBasicDto>> findAllDictTypeBasicBy(
        @Parameter(name = "dto", description = "", required = true, in = ParameterIn.QUERY) DictTypeQueryDto dto
    );


    /**
     * GET /dict-type
     *
     * @param dto  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "GET",
        value = "/dict-type",
        accept = { "*/*" }
    )
    ResponseEntity<List<DictTypeDto>> findAllDictTypeBy(
        @Parameter(name = "dto", description = "", required = true, in = ParameterIn.QUERY) DictTypeQueryDto dto
    );


    /**
     * GET /dict-type/page
     *
     * @param queryDto  (required)
     * @param pageNum  (optional, default to 1)
     * @param pageSize  (optional, default to 10)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "GET",
        value = "/dict-type/page",
        accept = { "*/*" }
    )
    ResponseEntity<PageResponseDtoDictTypeDto> findAllDictTypePageBy(
        @Parameter(name = "queryDto", description = "", required = true, in = ParameterIn.QUERY) DictTypeQueryDto queryDto,
        @Parameter(name = "pageNum", description = "", in = ParameterIn.QUERY) @RequestParam(value = "pageNum", required = false, defaultValue = "1") Integer pageNum,
        @Parameter(name = "pageSize", description = "", in = ParameterIn.QUERY) @RequestParam(value = "pageSize", required = false, defaultValue = "10") Integer pageSize
    );


    /**
     * GET /dict-type/{id}
     *
     * @param id  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "GET",
        value = "/dict-type/{id}",
        accept = { "*/*" }
    )
    ResponseEntity<DictTypeDto> findDictTypeById(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Long id
    );


    /**
     * PUT /dict-type/{id}
     *
     * @param id  (required)
     * @param dictTypeDto  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "PUT",
        value = "/dict-type/{id}",
        accept = { "application/json" },
        contentType = "application/json"
    )
    ResponseEntity<Void> updateDictTypeById(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Long id,
        @Parameter(name = "DictTypeDto", description = "", required = true) @RequestBody DictTypeDto dictTypeDto
    );

}
