/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.13.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.sct.system.client.api;

import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;

import com.sct.system.client.model.DictDto;
import com.sct.system.client.model.DictQueryDto;
import org.springframework.http.HttpStatus;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.service.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import org.springframework.http.codec.multipart.Part;
import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;

import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;


@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-08-02T16:25:21.114600400+08:00[Asia/Shanghai]", comments = "Generator version: 7.13.0")
public interface DictControllerApi {

    /**
     * GET /dict/count
     *
     * @param dto  (required)
     * @return OK (status code 200)
     */
    @ResponseStatus(HttpStatus.OK)
    @HttpExchange(
        method = "GET",
        value = "/dict/count",
        accept = { "*/*" }
    )
    Mono<Long> countAllDictBy(
        @Parameter(name = "dto", description = "", required = true, in = ParameterIn.QUERY) DictQueryDto dto
    );


    /**
     * POST /dict
     *
     * @param dictDto  (required)
     * @return OK (status code 200)
     */
    @ResponseStatus(HttpStatus.OK)
    @HttpExchange(
        method = "POST",
        value = "/dict",
        accept = { "application/json" },
        contentType = "application/json"
    )
    Mono<Void> createDict(
        @Parameter(name = "DictDto", description = "", required = true) @RequestBody Mono<DictDto> dictDto
    );


    /**
     * DELETE /dict/{id}
     *
     * @param id  (required)
     * @return OK (status code 200)
     */
    @ResponseStatus(HttpStatus.OK)
    @HttpExchange(
        method = "DELETE",
        value = "/dict/{id}",
        accept = { "application/json" }
    )
    Mono<Void> deleteDictById(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Long id
    );


    /**
     * GET /dict/basic
     *
     * @param dto  (required)
     * @return OK (status code 200)
     */
    @ResponseStatus(HttpStatus.OK)
    @HttpExchange(
        method = "GET",
        value = "/dict/basic",
        accept = { "*/*" }
    )
    Flux<DictDto> findAllDictBasicBy(
        @Parameter(name = "dto", description = "", required = true, in = ParameterIn.QUERY) DictQueryDto dto
    );


    /**
     * GET /dict
     *
     * @param dto  (required)
     * @return OK (status code 200)
     */
    @ResponseStatus(HttpStatus.OK)
    @HttpExchange(
        method = "GET",
        value = "/dict",
        accept = { "*/*" }
    )
    Flux<DictDto> findAllDictBy(
        @Parameter(name = "dto", description = "", required = true, in = ParameterIn.QUERY) DictQueryDto dto
    );


    /**
     * GET /dict/{id}
     *
     * @param id  (required)
     * @return OK (status code 200)
     */
    @ResponseStatus(HttpStatus.OK)
    @HttpExchange(
        method = "GET",
        value = "/dict/{id}",
        accept = { "*/*" }
    )
    Mono<DictDto> findDictById(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Long id
    );


    /**
     * PUT /dict/{id}
     *
     * @param id  (required)
     * @param dictDto  (required)
     * @return OK (status code 200)
     */
    @ResponseStatus(HttpStatus.OK)
    @HttpExchange(
        method = "PUT",
        value = "/dict/{id}",
        accept = { "application/json" },
        contentType = "application/json"
    )
    Mono<Void> updateDictById(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Long id,
        @Parameter(name = "DictDto", description = "", required = true) @RequestBody Mono<DictDto> dictDto
    );

}
