/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.17.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.sct.system.client.api;

import com.sct.system.client.model.DictTypeDto;
import com.sct.system.client.model.DictTypeQueryDto;
import com.sct.system.client.model.PageRequestDto;
import com.sct.system.client.model.PageResponseDtoDictTypeBasicDto;
import com.sct.system.client.model.PageResponseDtoDictTypeDto;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.service.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;


@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-12-11T14:51:39.505559+08:00[Asia/Shanghai]", comments = "Generator version: 7.17.0")
public interface DictTypeControllerApi {

    /**
     * GET /dict-type/count
     *
     * @param queryDto  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "GET",
        value = "/dict-type/count",
        accept = { "*/*" }
    )
    ResponseEntity<Long> countDictTypeBy(
        @Parameter(name = "queryDto", description = "", required = true, in = ParameterIn.QUERY) DictTypeQueryDto queryDto
    );


    /**
     * POST /dict-type
     *
     * @param dictTypeDto  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "POST",
        value = "/dict-type",
        accept = { "application/json" },
        contentType = "application/json"
    )
    ResponseEntity<Void> createDictType(
        @Parameter(name = "DictTypeDto", description = "", required = true) @RequestBody DictTypeDto dictTypeDto
    );


    /**
     * DELETE /dict-type/{id}
     *
     * @param id  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "DELETE",
        value = "/dict-type/{id}",
        accept = { "application/json" }
    )
    ResponseEntity<Void> deleteDictTypeById(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Long id
    );


    /**
     * GET /dict-type/basic
     *
     * @param queryDto  (required)
     * @param pageRequestDto  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "GET",
        value = "/dict-type/basic",
        accept = { "*/*" }
    )
    ResponseEntity<PageResponseDtoDictTypeBasicDto> findAllDictTypeBasicBy(
        @Parameter(name = "queryDto", description = "", required = true, in = ParameterIn.QUERY) DictTypeQueryDto queryDto,
        @Parameter(name = "pageRequestDto", description = "", required = true, in = ParameterIn.QUERY) PageRequestDto pageRequestDto
    );


    /**
     * GET /dict-type
     *
     * @param queryDto  (required)
     * @param pageRequestDto  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "GET",
        value = "/dict-type",
        accept = { "*/*" }
    )
    ResponseEntity<PageResponseDtoDictTypeDto> findAllDictTypeBy(
        @Parameter(name = "queryDto", description = "", required = true, in = ParameterIn.QUERY) DictTypeQueryDto queryDto,
        @Parameter(name = "pageRequestDto", description = "", required = true, in = ParameterIn.QUERY) PageRequestDto pageRequestDto
    );


    /**
     * GET /dict-type/{id}
     *
     * @param id  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "GET",
        value = "/dict-type/{id}",
        accept = { "*/*" }
    )
    ResponseEntity<DictTypeDto> getDictTypeById(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Long id
    );


    /**
     * PUT /dict-type/{id}
     *
     * @param id  (required)
     * @param dictTypeDto  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "PUT",
        value = "/dict-type/{id}",
        accept = { "application/json" },
        contentType = "application/json"
    )
    ResponseEntity<Void> updateDictTypeById(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Long id,
        @Parameter(name = "DictTypeDto", description = "", required = true) @RequestBody DictTypeDto dictTypeDto
    );

}
