/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.17.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.sct.system.client.api;

import com.sct.system.client.model.DictItemDto;
import com.sct.system.client.model.DictItemQueryDto;
import com.sct.system.client.model.PageRequestDto;
import com.sct.system.client.model.PageResponseDtoDictItemBasicDto;
import com.sct.system.client.model.PageResponseDtoDictItemDto;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.service.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;


@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-12-11T14:51:39.505559+08:00[Asia/Shanghai]", comments = "Generator version: 7.17.0")
public interface DictItemControllerApi {

    /**
     * GET /dict-item/count
     *
     * @param queryDto  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "GET",
        value = "/dict-item/count",
        accept = { "*/*" }
    )
    ResponseEntity<Long> countDictItemBy(
        @Parameter(name = "queryDto", description = "", required = true, in = ParameterIn.QUERY) DictItemQueryDto queryDto
    );


    /**
     * POST /dict-item
     *
     * @param dictItemDto  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "POST",
        value = "/dict-item",
        accept = { "application/json" },
        contentType = "application/json"
    )
    ResponseEntity<Void> createDictItem(
        @Parameter(name = "DictItemDto", description = "", required = true) @RequestBody DictItemDto dictItemDto
    );


    /**
     * DELETE /dict-item/{id}
     *
     * @param id  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "DELETE",
        value = "/dict-item/{id}",
        accept = { "application/json" }
    )
    ResponseEntity<Void> deleteDictItemById(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Long id
    );


    /**
     * GET /dict-item/basic
     *
     * @param queryDto  (required)
     * @param pageRequestDto  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "GET",
        value = "/dict-item/basic",
        accept = { "*/*" }
    )
    ResponseEntity<PageResponseDtoDictItemBasicDto> findAllDictItemBasicBy(
        @Parameter(name = "queryDto", description = "", required = true, in = ParameterIn.QUERY) DictItemQueryDto queryDto,
        @Parameter(name = "pageRequestDto", description = "", required = true, in = ParameterIn.QUERY) PageRequestDto pageRequestDto
    );


    /**
     * GET /dict-item
     *
     * @param queryDto  (required)
     * @param pageRequestDto  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "GET",
        value = "/dict-item",
        accept = { "*/*" }
    )
    ResponseEntity<PageResponseDtoDictItemDto> findAllDictItemBy(
        @Parameter(name = "queryDto", description = "", required = true, in = ParameterIn.QUERY) DictItemQueryDto queryDto,
        @Parameter(name = "pageRequestDto", description = "", required = true, in = ParameterIn.QUERY) PageRequestDto pageRequestDto
    );


    /**
     * GET /dict-item/{id}
     *
     * @param id  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "GET",
        value = "/dict-item/{id}",
        accept = { "*/*" }
    )
    ResponseEntity<DictItemDto> getDictItemById(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Long id
    );


    /**
     * PUT /dict-item/{id}
     *
     * @param id  (required)
     * @param dictItemDto  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "PUT",
        value = "/dict-item/{id}",
        accept = { "application/json" },
        contentType = "application/json"
    )
    ResponseEntity<Void> updateDictItemById(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Long id,
        @Parameter(name = "DictItemDto", description = "", required = true) @RequestBody DictItemDto dictItemDto
    );

}
