/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.17.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.sct.system.client.api;

import com.sct.system.client.model.DictBasicDto;
import com.sct.system.client.model.DictDto;
import com.sct.system.client.model.DictQueryDto;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.service.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;


@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-12-04T14:12:20.739110+08:00[Asia/Shanghai]", comments = "Generator version: 7.17.0")
public interface DictControllerApi {

    /**
     * GET /dict/count
     *
     * @param dto  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "GET",
        value = "/dict/count",
        accept = { "*/*" }
    )
    ResponseEntity<Long> countAllDictBy(
        @Parameter(name = "dto", description = "", required = true, in = ParameterIn.QUERY) DictQueryDto dto
    );


    /**
     * POST /dict
     *
     * @param dictDto  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "POST",
        value = "/dict",
        accept = { "application/json" },
        contentType = "application/json"
    )
    ResponseEntity<Void> createDict(
        @Parameter(name = "DictDto", description = "", required = true) @RequestBody DictDto dictDto
    );


    /**
     * DELETE /dict/{id}
     *
     * @param id  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "DELETE",
        value = "/dict/{id}",
        accept = { "application/json" }
    )
    ResponseEntity<Void> deleteDictById(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Long id
    );


    /**
     * GET /dict/basic
     *
     * @param dto  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "GET",
        value = "/dict/basic",
        accept = { "*/*" }
    )
    ResponseEntity<List<DictBasicDto>> findAllDictBasicBy(
        @Parameter(name = "dto", description = "", required = true, in = ParameterIn.QUERY) DictQueryDto dto
    );


    /**
     * GET /dict
     *
     * @param dto  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "GET",
        value = "/dict",
        accept = { "*/*" }
    )
    ResponseEntity<List<DictDto>> findAllDictBy(
        @Parameter(name = "dto", description = "", required = true, in = ParameterIn.QUERY) DictQueryDto dto
    );


    /**
     * GET /dict/{id}
     *
     * @param id  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "GET",
        value = "/dict/{id}",
        accept = { "*/*" }
    )
    ResponseEntity<DictDto> findDictById(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Long id
    );


    /**
     * PUT /dict/{id}
     *
     * @param id  (required)
     * @param dictDto  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "PUT",
        value = "/dict/{id}",
        accept = { "application/json" },
        contentType = "application/json"
    )
    ResponseEntity<Void> updateDictById(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Long id,
        @Parameter(name = "DictDto", description = "", required = true) @RequestBody DictDto dictDto
    );

}
