/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.17.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.sct.system.client.api;

import com.sct.system.client.model.DictItemBasicDto;
import com.sct.system.client.model.DictItemDto;
import com.sct.system.client.model.DictItemQueryDto;
import org.springframework.lang.Nullable;
import com.sct.system.client.model.PageResponseDtoDictItemDto;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.service.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;


@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-12-10T10:12:59.932325+08:00[Asia/Shanghai]", comments = "Generator version: 7.17.0")
public interface DictItemControllerApi {

    /**
     * GET /dict-item/count
     *
     * @param dto  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "GET",
        value = "/dict-item/count",
        accept = { "*/*" }
    )
    ResponseEntity<Long> countAllDictItemBy(
        @Parameter(name = "dto", description = "", required = true, in = ParameterIn.QUERY) DictItemQueryDto dto
    );


    /**
     * POST /dict-item
     *
     * @param dictItemDto  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "POST",
        value = "/dict-item",
        accept = { "application/json" },
        contentType = "application/json"
    )
    ResponseEntity<Void> createDictItem(
        @Parameter(name = "DictItemDto", description = "", required = true) @RequestBody DictItemDto dictItemDto
    );


    /**
     * DELETE /dict-item/{id}
     *
     * @param id  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "DELETE",
        value = "/dict-item/{id}",
        accept = { "application/json" }
    )
    ResponseEntity<Void> deleteDictItemById(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Long id
    );


    /**
     * GET /dict-item/basic
     *
     * @param dto  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "GET",
        value = "/dict-item/basic",
        accept = { "*/*" }
    )
    ResponseEntity<List<DictItemBasicDto>> findAllDictItemBasicBy(
        @Parameter(name = "dto", description = "", required = true, in = ParameterIn.QUERY) DictItemQueryDto dto
    );


    /**
     * GET /dict-item
     *
     * @param dto  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "GET",
        value = "/dict-item",
        accept = { "*/*" }
    )
    ResponseEntity<List<DictItemDto>> findAllDictItemBy(
        @Parameter(name = "dto", description = "", required = true, in = ParameterIn.QUERY) DictItemQueryDto dto
    );


    /**
     * GET /dict-item/page
     *
     * @param queryDto  (required)
     * @param pageNum  (optional, default to 1)
     * @param pageSize  (optional, default to 10)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "GET",
        value = "/dict-item/page",
        accept = { "*/*" }
    )
    ResponseEntity<PageResponseDtoDictItemDto> findAllDictItemPageBy(
        @Parameter(name = "queryDto", description = "", required = true, in = ParameterIn.QUERY) DictItemQueryDto queryDto,
        @Parameter(name = "pageNum", description = "", in = ParameterIn.QUERY) @RequestParam(value = "pageNum", required = false, defaultValue = "1") Integer pageNum,
        @Parameter(name = "pageSize", description = "", in = ParameterIn.QUERY) @RequestParam(value = "pageSize", required = false, defaultValue = "10") Integer pageSize
    );


    /**
     * GET /dict-item/{id}
     *
     * @param id  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "GET",
        value = "/dict-item/{id}",
        accept = { "*/*" }
    )
    ResponseEntity<DictItemDto> findDictItemById(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Long id
    );


    /**
     * PUT /dict-item/{id}
     *
     * @param id  (required)
     * @param dictItemDto  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "PUT",
        value = "/dict-item/{id}",
        accept = { "application/json" },
        contentType = "application/json"
    )
    ResponseEntity<Void> updateDictItemById(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Long id,
        @Parameter(name = "DictItemDto", description = "", required = true) @RequestBody DictItemDto dictItemDto
    );

}
