/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.17.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.sct.system.client.api;

import com.sct.system.client.model.LoginLogDto;
import com.sct.system.client.model.LoginLogQueryDto;
import com.sct.system.client.model.PageRequestDto;
import com.sct.system.client.model.PageResponseDtoLoginLogBasicDto;
import com.sct.system.client.model.PageResponseDtoLoginLogDto;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.service.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;


@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-12-11T14:51:39.505559+08:00[Asia/Shanghai]", comments = "Generator version: 7.17.0")
public interface LoginLogControllerApi {

    /**
     * GET /login-log/count
     *
     * @param queryDto  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "GET",
        value = "/login-log/count",
        accept = { "*/*" }
    )
    ResponseEntity<Long> countLoginLogBy(
        @Parameter(name = "queryDto", description = "", required = true, in = ParameterIn.QUERY) LoginLogQueryDto queryDto
    );


    /**
     * POST /login-log
     *
     * @param loginLogDto  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "POST",
        value = "/login-log",
        accept = { "application/json" },
        contentType = "application/json"
    )
    ResponseEntity<Void> createLoginLog(
        @Parameter(name = "LoginLogDto", description = "", required = true) @RequestBody LoginLogDto loginLogDto
    );


    /**
     * DELETE /login-log/{id}
     *
     * @param id  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "DELETE",
        value = "/login-log/{id}",
        accept = { "application/json" }
    )
    ResponseEntity<Void> deleteLoginLogById(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Long id
    );


    /**
     * GET /login-log/basic
     *
     * @param queryDto  (required)
     * @param pageRequestDto  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "GET",
        value = "/login-log/basic",
        accept = { "*/*" }
    )
    ResponseEntity<PageResponseDtoLoginLogBasicDto> findAllLoginLogBasicBy(
        @Parameter(name = "queryDto", description = "", required = true, in = ParameterIn.QUERY) LoginLogQueryDto queryDto,
        @Parameter(name = "pageRequestDto", description = "", required = true, in = ParameterIn.QUERY) PageRequestDto pageRequestDto
    );


    /**
     * GET /login-log
     *
     * @param queryDto  (required)
     * @param pageRequestDto  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "GET",
        value = "/login-log",
        accept = { "*/*" }
    )
    ResponseEntity<PageResponseDtoLoginLogDto> findAllLoginLogBy(
        @Parameter(name = "queryDto", description = "", required = true, in = ParameterIn.QUERY) LoginLogQueryDto queryDto,
        @Parameter(name = "pageRequestDto", description = "", required = true, in = ParameterIn.QUERY) PageRequestDto pageRequestDto
    );


    /**
     * GET /login-log/{id}
     *
     * @param id  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "GET",
        value = "/login-log/{id}",
        accept = { "*/*" }
    )
    ResponseEntity<LoginLogDto> getLoginLogById(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Long id
    );


    /**
     * PUT /login-log/{id}
     *
     * @param id  (required)
     * @param loginLogDto  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "PUT",
        value = "/login-log/{id}",
        accept = { "application/json" },
        contentType = "application/json"
    )
    ResponseEntity<Void> updateLoginLogById(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Long id,
        @Parameter(name = "LoginLogDto", description = "", required = true) @RequestBody LoginLogDto loginLogDto
    );

}
