/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.17.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.sct.system.client.api;

import com.sct.system.client.model.LoginLogBasicDto;
import com.sct.system.client.model.LoginLogDto;
import com.sct.system.client.model.LoginLogQueryDto;
import org.springframework.lang.Nullable;
import com.sct.system.client.model.PageResponseDtoLoginLogDto;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.service.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;


@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-12-10T10:12:59.932325+08:00[Asia/Shanghai]", comments = "Generator version: 7.17.0")
public interface LoginLogControllerApi {

    /**
     * GET /login-log/count
     *
     * @param dto  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "GET",
        value = "/login-log/count",
        accept = { "*/*" }
    )
    ResponseEntity<Long> countAllLoginLogBy(
        @Parameter(name = "dto", description = "", required = true, in = ParameterIn.QUERY) LoginLogQueryDto dto
    );


    /**
     * POST /login-log
     *
     * @param loginLogDto  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "POST",
        value = "/login-log",
        accept = { "application/json" },
        contentType = "application/json"
    )
    ResponseEntity<Void> createLoginLog(
        @Parameter(name = "LoginLogDto", description = "", required = true) @RequestBody LoginLogDto loginLogDto
    );


    /**
     * DELETE /login-log/{id}
     *
     * @param id  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "DELETE",
        value = "/login-log/{id}",
        accept = { "application/json" }
    )
    ResponseEntity<Void> deleteLoginLogById(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Long id
    );


    /**
     * GET /login-log/basic
     *
     * @param dto  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "GET",
        value = "/login-log/basic",
        accept = { "*/*" }
    )
    ResponseEntity<List<LoginLogBasicDto>> findAllLoginLogBasicBy(
        @Parameter(name = "dto", description = "", required = true, in = ParameterIn.QUERY) LoginLogQueryDto dto
    );


    /**
     * GET /login-log
     *
     * @param dto  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "GET",
        value = "/login-log",
        accept = { "*/*" }
    )
    ResponseEntity<List<LoginLogDto>> findAllLoginLogBy(
        @Parameter(name = "dto", description = "", required = true, in = ParameterIn.QUERY) LoginLogQueryDto dto
    );


    /**
     * GET /login-log/page
     *
     * @param queryDto  (required)
     * @param pageNum  (optional, default to 1)
     * @param pageSize  (optional, default to 10)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "GET",
        value = "/login-log/page",
        accept = { "*/*" }
    )
    ResponseEntity<PageResponseDtoLoginLogDto> findAllLoginLogPageBy(
        @Parameter(name = "queryDto", description = "", required = true, in = ParameterIn.QUERY) LoginLogQueryDto queryDto,
        @Parameter(name = "pageNum", description = "", in = ParameterIn.QUERY) @RequestParam(value = "pageNum", required = false, defaultValue = "1") Integer pageNum,
        @Parameter(name = "pageSize", description = "", in = ParameterIn.QUERY) @RequestParam(value = "pageSize", required = false, defaultValue = "10") Integer pageSize
    );


    /**
     * GET /login-log/{id}
     *
     * @param id  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "GET",
        value = "/login-log/{id}",
        accept = { "*/*" }
    )
    ResponseEntity<LoginLogDto> findLoginLogById(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Long id
    );


    /**
     * PUT /login-log/{id}
     *
     * @param id  (required)
     * @param loginLogDto  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "PUT",
        value = "/login-log/{id}",
        accept = { "application/json" },
        contentType = "application/json"
    )
    ResponseEntity<Void> updateLoginLogById(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Long id,
        @Parameter(name = "LoginLogDto", description = "", required = true) @RequestBody LoginLogDto loginLogDto
    );

}
