/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.17.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.sct.system.client.api;

import com.sct.system.client.model.MenuBasicDto;
import com.sct.system.client.model.MenuDto;
import com.sct.system.client.model.MenuQueryDto;
import org.springframework.lang.Nullable;
import com.sct.system.client.model.PageResponseDtoMenuDto;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.service.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;


@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-12-10T10:12:59.932325+08:00[Asia/Shanghai]", comments = "Generator version: 7.17.0")
public interface MenuControllerApi {

    /**
     * GET /menu/count
     *
     * @param dto  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "GET",
        value = "/menu/count",
        accept = { "*/*" }
    )
    ResponseEntity<Long> countAllMenuBy(
        @Parameter(name = "dto", description = "", required = true, in = ParameterIn.QUERY) MenuQueryDto dto
    );


    /**
     * POST /menu
     *
     * @param menuDto  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "POST",
        value = "/menu",
        accept = { "application/json" },
        contentType = "application/json"
    )
    ResponseEntity<Void> createMenu(
        @Parameter(name = "MenuDto", description = "", required = true) @RequestBody MenuDto menuDto
    );


    /**
     * DELETE /menu/{id}
     *
     * @param id  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "DELETE",
        value = "/menu/{id}",
        accept = { "application/json" }
    )
    ResponseEntity<Void> deleteMenuById(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Long id
    );


    /**
     * GET /menu/basic
     *
     * @param dto  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "GET",
        value = "/menu/basic",
        accept = { "*/*" }
    )
    ResponseEntity<List<MenuBasicDto>> findAllMenuBasicBy(
        @Parameter(name = "dto", description = "", required = true, in = ParameterIn.QUERY) MenuQueryDto dto
    );


    /**
     * GET /menu
     *
     * @param dto  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "GET",
        value = "/menu",
        accept = { "*/*" }
    )
    ResponseEntity<List<MenuDto>> findAllMenuBy(
        @Parameter(name = "dto", description = "", required = true, in = ParameterIn.QUERY) MenuQueryDto dto
    );


    /**
     * GET /menu/page
     *
     * @param queryDto  (required)
     * @param pageNum  (optional, default to 1)
     * @param pageSize  (optional, default to 10)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "GET",
        value = "/menu/page",
        accept = { "*/*" }
    )
    ResponseEntity<PageResponseDtoMenuDto> findAllMenuPageBy(
        @Parameter(name = "queryDto", description = "", required = true, in = ParameterIn.QUERY) MenuQueryDto queryDto,
        @Parameter(name = "pageNum", description = "", in = ParameterIn.QUERY) @RequestParam(value = "pageNum", required = false, defaultValue = "1") Integer pageNum,
        @Parameter(name = "pageSize", description = "", in = ParameterIn.QUERY) @RequestParam(value = "pageSize", required = false, defaultValue = "10") Integer pageSize
    );


    /**
     * GET /menu/{id}
     *
     * @param id  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "GET",
        value = "/menu/{id}",
        accept = { "*/*" }
    )
    ResponseEntity<MenuDto> findMenuById(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Long id
    );


    /**
     * PUT /menu/{id}
     *
     * @param id  (required)
     * @param menuDto  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "PUT",
        value = "/menu/{id}",
        accept = { "application/json" },
        contentType = "application/json"
    )
    ResponseEntity<Void> updateMenuById(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Long id,
        @Parameter(name = "MenuDto", description = "", required = true) @RequestBody MenuDto menuDto
    );

}
