/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.17.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.sct.system.client.api;

import com.sct.system.client.model.OperationLogDto;
import com.sct.system.client.model.OperationLogQueryDto;
import com.sct.system.client.model.PageRequestDto;
import com.sct.system.client.model.PageResponseDtoOperationLogBasicDto;
import com.sct.system.client.model.PageResponseDtoOperationLogDto;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.service.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;


@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-12-11T14:51:39.505559+08:00[Asia/Shanghai]", comments = "Generator version: 7.17.0")
public interface OperationLogControllerApi {

    /**
     * GET /operation-log/count
     *
     * @param queryDto  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "GET",
        value = "/operation-log/count",
        accept = { "*/*" }
    )
    ResponseEntity<Long> countOperationLogBy(
        @Parameter(name = "queryDto", description = "", required = true, in = ParameterIn.QUERY) OperationLogQueryDto queryDto
    );


    /**
     * POST /operation-log
     *
     * @param operationLogDto  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "POST",
        value = "/operation-log",
        accept = { "application/json" },
        contentType = "application/json"
    )
    ResponseEntity<Void> createOperationLog(
        @Parameter(name = "OperationLogDto", description = "", required = true) @RequestBody OperationLogDto operationLogDto
    );


    /**
     * DELETE /operation-log/{id}
     *
     * @param id  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "DELETE",
        value = "/operation-log/{id}",
        accept = { "application/json" }
    )
    ResponseEntity<Void> deleteOperationLogById(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Long id
    );


    /**
     * GET /operation-log/basic
     *
     * @param queryDto  (required)
     * @param pageRequestDto  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "GET",
        value = "/operation-log/basic",
        accept = { "*/*" }
    )
    ResponseEntity<PageResponseDtoOperationLogBasicDto> findAllOperationLogBasicBy(
        @Parameter(name = "queryDto", description = "", required = true, in = ParameterIn.QUERY) OperationLogQueryDto queryDto,
        @Parameter(name = "pageRequestDto", description = "", required = true, in = ParameterIn.QUERY) PageRequestDto pageRequestDto
    );


    /**
     * GET /operation-log
     *
     * @param queryDto  (required)
     * @param pageRequestDto  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "GET",
        value = "/operation-log",
        accept = { "*/*" }
    )
    ResponseEntity<PageResponseDtoOperationLogDto> findAllOperationLogBy(
        @Parameter(name = "queryDto", description = "", required = true, in = ParameterIn.QUERY) OperationLogQueryDto queryDto,
        @Parameter(name = "pageRequestDto", description = "", required = true, in = ParameterIn.QUERY) PageRequestDto pageRequestDto
    );


    /**
     * GET /operation-log/{id}
     *
     * @param id  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "GET",
        value = "/operation-log/{id}",
        accept = { "*/*" }
    )
    ResponseEntity<OperationLogDto> getOperationLogById(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Long id
    );


    /**
     * PUT /operation-log/{id}
     *
     * @param id  (required)
     * @param operationLogDto  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "PUT",
        value = "/operation-log/{id}",
        accept = { "application/json" },
        contentType = "application/json"
    )
    ResponseEntity<Void> updateOperationLogById(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Long id,
        @Parameter(name = "OperationLogDto", description = "", required = true) @RequestBody OperationLogDto operationLogDto
    );

}
