/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.17.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.sct.system.client.api;

import org.springframework.lang.Nullable;
import com.sct.system.client.model.OperationLogBasicDto;
import com.sct.system.client.model.OperationLogDto;
import com.sct.system.client.model.OperationLogQueryDto;
import com.sct.system.client.model.PageResponseDtoOperationLogDto;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.service.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;


@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-12-10T10:12:59.932325+08:00[Asia/Shanghai]", comments = "Generator version: 7.17.0")
public interface OperationLogControllerApi {

    /**
     * GET /operation-log/count
     *
     * @param dto  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "GET",
        value = "/operation-log/count",
        accept = { "*/*" }
    )
    ResponseEntity<Long> countAllOperationLogBy(
        @Parameter(name = "dto", description = "", required = true, in = ParameterIn.QUERY) OperationLogQueryDto dto
    );


    /**
     * POST /operation-log
     *
     * @param operationLogDto  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "POST",
        value = "/operation-log",
        accept = { "application/json" },
        contentType = "application/json"
    )
    ResponseEntity<Void> createOperationLog(
        @Parameter(name = "OperationLogDto", description = "", required = true) @RequestBody OperationLogDto operationLogDto
    );


    /**
     * DELETE /operation-log/{id}
     *
     * @param id  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "DELETE",
        value = "/operation-log/{id}",
        accept = { "application/json" }
    )
    ResponseEntity<Void> deleteOperationLogById(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Long id
    );


    /**
     * GET /operation-log/basic
     *
     * @param dto  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "GET",
        value = "/operation-log/basic",
        accept = { "*/*" }
    )
    ResponseEntity<List<OperationLogBasicDto>> findAllOperationLogBasicBy(
        @Parameter(name = "dto", description = "", required = true, in = ParameterIn.QUERY) OperationLogQueryDto dto
    );


    /**
     * GET /operation-log
     *
     * @param dto  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "GET",
        value = "/operation-log",
        accept = { "*/*" }
    )
    ResponseEntity<List<OperationLogDto>> findAllOperationLogBy(
        @Parameter(name = "dto", description = "", required = true, in = ParameterIn.QUERY) OperationLogQueryDto dto
    );


    /**
     * GET /operation-log/page
     *
     * @param queryDto  (required)
     * @param pageNum  (optional, default to 1)
     * @param pageSize  (optional, default to 10)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "GET",
        value = "/operation-log/page",
        accept = { "*/*" }
    )
    ResponseEntity<PageResponseDtoOperationLogDto> findAllOperationLogPageBy(
        @Parameter(name = "queryDto", description = "", required = true, in = ParameterIn.QUERY) OperationLogQueryDto queryDto,
        @Parameter(name = "pageNum", description = "", in = ParameterIn.QUERY) @RequestParam(value = "pageNum", required = false, defaultValue = "1") Integer pageNum,
        @Parameter(name = "pageSize", description = "", in = ParameterIn.QUERY) @RequestParam(value = "pageSize", required = false, defaultValue = "10") Integer pageSize
    );


    /**
     * GET /operation-log/{id}
     *
     * @param id  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "GET",
        value = "/operation-log/{id}",
        accept = { "*/*" }
    )
    ResponseEntity<OperationLogDto> findOperationLogById(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Long id
    );


    /**
     * PUT /operation-log/{id}
     *
     * @param id  (required)
     * @param operationLogDto  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "PUT",
        value = "/operation-log/{id}",
        accept = { "application/json" },
        contentType = "application/json"
    )
    ResponseEntity<Void> updateOperationLogById(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Long id,
        @Parameter(name = "OperationLogDto", description = "", required = true) @RequestBody OperationLogDto operationLogDto
    );

}
