/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.17.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.sct.system.client.api;

import com.sct.system.client.model.OrgBasicDto;
import com.sct.system.client.model.OrgDto;
import com.sct.system.client.model.OrgQueryDto;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.service.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;


@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-12-04T14:12:20.739110+08:00[Asia/Shanghai]", comments = "Generator version: 7.17.0")
public interface OrgControllerApi {

    /**
     * GET /org/count
     *
     * @param dto  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "GET",
        value = "/org/count",
        accept = { "*/*" }
    )
    ResponseEntity<Long> countAllOrgBy(
        @Parameter(name = "dto", description = "", required = true, in = ParameterIn.QUERY) OrgQueryDto dto
    );


    /**
     * POST /org
     *
     * @param orgDto  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "POST",
        value = "/org",
        accept = { "application/json" },
        contentType = "application/json"
    )
    ResponseEntity<Void> createOrg(
        @Parameter(name = "OrgDto", description = "", required = true) @RequestBody OrgDto orgDto
    );


    /**
     * DELETE /org/{id}
     *
     * @param id  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "DELETE",
        value = "/org/{id}",
        accept = { "application/json" }
    )
    ResponseEntity<Void> deleteOrgById(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Long id
    );


    /**
     * GET /org/basic
     *
     * @param dto  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "GET",
        value = "/org/basic",
        accept = { "*/*" }
    )
    ResponseEntity<List<OrgBasicDto>> findAllOrgBasicBy(
        @Parameter(name = "dto", description = "", required = true, in = ParameterIn.QUERY) OrgQueryDto dto
    );


    /**
     * GET /org
     *
     * @param dto  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "GET",
        value = "/org",
        accept = { "*/*" }
    )
    ResponseEntity<List<OrgDto>> findAllOrgBy(
        @Parameter(name = "dto", description = "", required = true, in = ParameterIn.QUERY) OrgQueryDto dto
    );


    /**
     * GET /org/{id}
     *
     * @param id  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "GET",
        value = "/org/{id}",
        accept = { "*/*" }
    )
    ResponseEntity<OrgDto> findOrgById(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Long id
    );


    /**
     * PUT /org/{id}
     *
     * @param id  (required)
     * @param orgDto  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "PUT",
        value = "/org/{id}",
        accept = { "application/json" },
        contentType = "application/json"
    )
    ResponseEntity<Void> updateOrgById(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Long id,
        @Parameter(name = "OrgDto", description = "", required = true) @RequestBody OrgDto orgDto
    );

}
