/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.13.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.sct.system.client.api;

import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;

import com.sct.system.client.model.OrgDto;
import com.sct.system.client.model.OrgQueryDto;
import org.springframework.http.HttpStatus;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.service.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import org.springframework.http.codec.multipart.Part;
import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;

import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;


@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-08-02T16:25:21.114600400+08:00[Asia/Shanghai]", comments = "Generator version: 7.13.0")
public interface OrgControllerApi {

    /**
     * GET /org/count
     *
     * @param dto  (required)
     * @return OK (status code 200)
     */
    @ResponseStatus(HttpStatus.OK)
    @HttpExchange(
        method = "GET",
        value = "/org/count",
        accept = { "*/*" }
    )
    Mono<Long> countAllOrgBy(
        @Parameter(name = "dto", description = "", required = true, in = ParameterIn.QUERY) OrgQueryDto dto
    );


    /**
     * POST /org
     *
     * @param orgDto  (required)
     * @return OK (status code 200)
     */
    @ResponseStatus(HttpStatus.OK)
    @HttpExchange(
        method = "POST",
        value = "/org",
        accept = { "application/json" },
        contentType = "application/json"
    )
    Mono<Void> createOrg(
        @Parameter(name = "OrgDto", description = "", required = true) @RequestBody Mono<OrgDto> orgDto
    );


    /**
     * DELETE /org/{id}
     *
     * @param id  (required)
     * @return OK (status code 200)
     */
    @ResponseStatus(HttpStatus.OK)
    @HttpExchange(
        method = "DELETE",
        value = "/org/{id}",
        accept = { "application/json" }
    )
    Mono<Void> deleteOrgById(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Long id
    );


    /**
     * GET /org/basic
     *
     * @param dto  (required)
     * @return OK (status code 200)
     */
    @ResponseStatus(HttpStatus.OK)
    @HttpExchange(
        method = "GET",
        value = "/org/basic",
        accept = { "*/*" }
    )
    Flux<OrgDto> findAllOrgBasicBy(
        @Parameter(name = "dto", description = "", required = true, in = ParameterIn.QUERY) OrgQueryDto dto
    );


    /**
     * GET /org
     *
     * @param dto  (required)
     * @return OK (status code 200)
     */
    @ResponseStatus(HttpStatus.OK)
    @HttpExchange(
        method = "GET",
        value = "/org",
        accept = { "*/*" }
    )
    Flux<OrgDto> findAllOrgBy(
        @Parameter(name = "dto", description = "", required = true, in = ParameterIn.QUERY) OrgQueryDto dto
    );


    /**
     * GET /org/{id}
     *
     * @param id  (required)
     * @return OK (status code 200)
     */
    @ResponseStatus(HttpStatus.OK)
    @HttpExchange(
        method = "GET",
        value = "/org/{id}",
        accept = { "*/*" }
    )
    Mono<OrgDto> findOrgById(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Long id
    );


    /**
     * PUT /org/{id}
     *
     * @param id  (required)
     * @param orgDto  (required)
     * @return OK (status code 200)
     */
    @ResponseStatus(HttpStatus.OK)
    @HttpExchange(
        method = "PUT",
        value = "/org/{id}",
        accept = { "application/json" },
        contentType = "application/json"
    )
    Mono<Void> updateOrgById(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Long id,
        @Parameter(name = "OrgDto", description = "", required = true) @RequestBody Mono<OrgDto> orgDto
    );

}
