/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.13.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.sct.system.client.api;

import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;

import com.sct.system.client.model.ParamBasicDto;
import com.sct.system.client.model.ParamDto;
import com.sct.system.client.model.ParamQueryDto;
import org.springframework.http.HttpStatus;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.service.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import org.springframework.http.codec.multipart.Part;
import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;

import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;


@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-08-02T16:30:52.304240400+08:00[Asia/Shanghai]", comments = "Generator version: 7.13.0")
public interface ParamControllerApi {

    /**
     * GET /param/count
     *
     * @param dto  (required)
     * @return OK (status code 200)
     */
    @ResponseStatus(HttpStatus.OK)
    @HttpExchange(
        method = "GET",
        value = "/param/count",
        accept = { "*/*" }
    )
    Mono<Long> countAllParamBy(
        @Parameter(name = "dto", description = "", required = true, in = ParameterIn.QUERY) ParamQueryDto dto
    );


    /**
     * POST /param
     *
     * @param paramDto  (required)
     * @return OK (status code 200)
     */
    @ResponseStatus(HttpStatus.OK)
    @HttpExchange(
        method = "POST",
        value = "/param",
        accept = { "application/json" },
        contentType = "application/json"
    )
    Mono<Void> createParam(
        @Parameter(name = "ParamDto", description = "", required = true) @RequestBody Mono<ParamDto> paramDto
    );


    /**
     * DELETE /param/{id}
     *
     * @param id  (required)
     * @return OK (status code 200)
     */
    @ResponseStatus(HttpStatus.OK)
    @HttpExchange(
        method = "DELETE",
        value = "/param/{id}",
        accept = { "application/json" }
    )
    Mono<Void> deleteParamById(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Long id
    );


    /**
     * GET /param/basic
     *
     * @param dto  (required)
     * @return OK (status code 200)
     */
    @ResponseStatus(HttpStatus.OK)
    @HttpExchange(
        method = "GET",
        value = "/param/basic",
        accept = { "*/*" }
    )
    Flux<ParamBasicDto> findAllParamBasicBy(
        @Parameter(name = "dto", description = "", required = true, in = ParameterIn.QUERY) ParamQueryDto dto
    );


    /**
     * GET /param
     *
     * @param dto  (required)
     * @return OK (status code 200)
     */
    @ResponseStatus(HttpStatus.OK)
    @HttpExchange(
        method = "GET",
        value = "/param",
        accept = { "*/*" }
    )
    Flux<ParamDto> findAllParamBy(
        @Parameter(name = "dto", description = "", required = true, in = ParameterIn.QUERY) ParamQueryDto dto
    );


    /**
     * GET /param/{id}
     *
     * @param id  (required)
     * @return OK (status code 200)
     */
    @ResponseStatus(HttpStatus.OK)
    @HttpExchange(
        method = "GET",
        value = "/param/{id}",
        accept = { "*/*" }
    )
    Mono<ParamDto> findParamById(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Long id
    );


    /**
     * PUT /param/{id}
     *
     * @param id  (required)
     * @param paramDto  (required)
     * @return OK (status code 200)
     */
    @ResponseStatus(HttpStatus.OK)
    @HttpExchange(
        method = "PUT",
        value = "/param/{id}",
        accept = { "application/json" },
        contentType = "application/json"
    )
    Mono<Void> updateParamById(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Long id,
        @Parameter(name = "ParamDto", description = "", required = true) @RequestBody Mono<ParamDto> paramDto
    );

}
