/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.17.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.sct.system.client.api;

import com.sct.system.client.model.PageRequestDto;
import com.sct.system.client.model.PageResponseDtoRoleBasicDto;
import com.sct.system.client.model.PageResponseDtoRoleDto;
import com.sct.system.client.model.RoleDto;
import com.sct.system.client.model.RoleQueryDto;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.service.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;


@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-12-11T14:51:39.505559+08:00[Asia/Shanghai]", comments = "Generator version: 7.17.0")
public interface RoleControllerApi {

    /**
     * GET /role/count
     *
     * @param queryDto  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "GET",
        value = "/role/count",
        accept = { "*/*" }
    )
    ResponseEntity<Long> countRoleBy(
        @Parameter(name = "queryDto", description = "", required = true, in = ParameterIn.QUERY) RoleQueryDto queryDto
    );


    /**
     * POST /role
     *
     * @param roleDto  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "POST",
        value = "/role",
        accept = { "application/json" },
        contentType = "application/json"
    )
    ResponseEntity<Void> createRole(
        @Parameter(name = "RoleDto", description = "", required = true) @RequestBody RoleDto roleDto
    );


    /**
     * DELETE /role/{id}
     *
     * @param id  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "DELETE",
        value = "/role/{id}",
        accept = { "application/json" }
    )
    ResponseEntity<Void> deleteRoleById(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Long id
    );


    /**
     * GET /role/basic
     *
     * @param queryDto  (required)
     * @param pageRequestDto  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "GET",
        value = "/role/basic",
        accept = { "*/*" }
    )
    ResponseEntity<PageResponseDtoRoleBasicDto> findAllRoleBasicBy(
        @Parameter(name = "queryDto", description = "", required = true, in = ParameterIn.QUERY) RoleQueryDto queryDto,
        @Parameter(name = "pageRequestDto", description = "", required = true, in = ParameterIn.QUERY) PageRequestDto pageRequestDto
    );


    /**
     * GET /role
     *
     * @param queryDto  (required)
     * @param pageRequestDto  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "GET",
        value = "/role",
        accept = { "*/*" }
    )
    ResponseEntity<PageResponseDtoRoleDto> findAllRoleBy(
        @Parameter(name = "queryDto", description = "", required = true, in = ParameterIn.QUERY) RoleQueryDto queryDto,
        @Parameter(name = "pageRequestDto", description = "", required = true, in = ParameterIn.QUERY) PageRequestDto pageRequestDto
    );


    /**
     * GET /role/{id}
     *
     * @param id  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "GET",
        value = "/role/{id}",
        accept = { "*/*" }
    )
    ResponseEntity<RoleDto> getRoleById(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Long id
    );


    /**
     * PUT /role/{id}
     *
     * @param id  (required)
     * @param roleDto  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "PUT",
        value = "/role/{id}",
        accept = { "application/json" },
        contentType = "application/json"
    )
    ResponseEntity<Void> updateRoleById(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Long id,
        @Parameter(name = "RoleDto", description = "", required = true) @RequestBody RoleDto roleDto
    );

}
