/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.17.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.sct.system.client.api;

import org.springframework.lang.Nullable;
import com.sct.system.client.model.PageResponseDtoRoleDto;
import com.sct.system.client.model.RoleBasicDto;
import com.sct.system.client.model.RoleDto;
import com.sct.system.client.model.RoleQueryDto;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.service.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;


@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-12-06T19:37:11.351265800+08:00[Asia/Shanghai]", comments = "Generator version: 7.17.0")
public interface RoleControllerApi {

    /**
     * GET /role/count
     *
     * @param dto  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "GET",
        value = "/role/count",
        accept = { "*/*" }
    )
    ResponseEntity<Long> countAllRoleBy(
        @Parameter(name = "dto", description = "", required = true, in = ParameterIn.QUERY) RoleQueryDto dto
    );


    /**
     * POST /role
     *
     * @param roleDto  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "POST",
        value = "/role",
        accept = { "application/json" },
        contentType = "application/json"
    )
    ResponseEntity<Void> createRole(
        @Parameter(name = "RoleDto", description = "", required = true) @RequestBody RoleDto roleDto
    );


    /**
     * DELETE /role/{id}
     *
     * @param id  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "DELETE",
        value = "/role/{id}",
        accept = { "application/json" }
    )
    ResponseEntity<Void> deleteRoleById(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Long id
    );


    /**
     * GET /role/basic
     *
     * @param dto  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "GET",
        value = "/role/basic",
        accept = { "*/*" }
    )
    ResponseEntity<List<RoleBasicDto>> findAllRoleBasicBy(
        @Parameter(name = "dto", description = "", required = true, in = ParameterIn.QUERY) RoleQueryDto dto
    );


    /**
     * GET /role
     *
     * @param dto  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "GET",
        value = "/role",
        accept = { "*/*" }
    )
    ResponseEntity<List<RoleDto>> findAllRoleBy(
        @Parameter(name = "dto", description = "", required = true, in = ParameterIn.QUERY) RoleQueryDto dto
    );


    /**
     * GET /role/page
     *
     * @param queryDto  (required)
     * @param pageNum  (optional, default to 1)
     * @param pageSize  (optional, default to 10)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "GET",
        value = "/role/page",
        accept = { "*/*" }
    )
    ResponseEntity<PageResponseDtoRoleDto> findAllRolePageBy(
        @Parameter(name = "queryDto", description = "", required = true, in = ParameterIn.QUERY) RoleQueryDto queryDto,
        @Parameter(name = "pageNum", description = "", in = ParameterIn.QUERY) @RequestParam(value = "pageNum", required = false, defaultValue = "1") Integer pageNum,
        @Parameter(name = "pageSize", description = "", in = ParameterIn.QUERY) @RequestParam(value = "pageSize", required = false, defaultValue = "10") Integer pageSize
    );


    /**
     * GET /role/{id}
     *
     * @param id  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "GET",
        value = "/role/{id}",
        accept = { "*/*" }
    )
    ResponseEntity<RoleDto> findRoleById(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Long id
    );


    /**
     * PUT /role/{id}
     *
     * @param id  (required)
     * @param roleDto  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "PUT",
        value = "/role/{id}",
        accept = { "application/json" },
        contentType = "application/json"
    )
    ResponseEntity<Void> updateRoleById(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Long id,
        @Parameter(name = "RoleDto", description = "", required = true) @RequestBody RoleDto roleDto
    );

}
