/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.13.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.sct.system.client.api;

import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;

import com.sct.system.client.model.RoleBasicDto;
import com.sct.system.client.model.RoleDto;
import com.sct.system.client.model.RoleQueryDto;
import org.springframework.http.HttpStatus;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.service.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import org.springframework.http.codec.multipart.Part;
import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;

import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;


@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-08-02T16:30:52.304240400+08:00[Asia/Shanghai]", comments = "Generator version: 7.13.0")
public interface RoleControllerApi {

    /**
     * GET /role/count
     *
     * @param dto  (required)
     * @return OK (status code 200)
     */
    @ResponseStatus(HttpStatus.OK)
    @HttpExchange(
        method = "GET",
        value = "/role/count",
        accept = { "*/*" }
    )
    Mono<Long> countAllRoleBy(
        @Parameter(name = "dto", description = "", required = true, in = ParameterIn.QUERY) RoleQueryDto dto
    );


    /**
     * POST /role
     *
     * @param roleDto  (required)
     * @return OK (status code 200)
     */
    @ResponseStatus(HttpStatus.OK)
    @HttpExchange(
        method = "POST",
        value = "/role",
        accept = { "application/json" },
        contentType = "application/json"
    )
    Mono<Void> createRole(
        @Parameter(name = "RoleDto", description = "", required = true) @RequestBody Mono<RoleDto> roleDto
    );


    /**
     * DELETE /role/{id}
     *
     * @param id  (required)
     * @return OK (status code 200)
     */
    @ResponseStatus(HttpStatus.OK)
    @HttpExchange(
        method = "DELETE",
        value = "/role/{id}",
        accept = { "application/json" }
    )
    Mono<Void> deleteRoleById(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Long id
    );


    /**
     * GET /role/basic
     *
     * @param dto  (required)
     * @return OK (status code 200)
     */
    @ResponseStatus(HttpStatus.OK)
    @HttpExchange(
        method = "GET",
        value = "/role/basic",
        accept = { "*/*" }
    )
    Flux<RoleBasicDto> findAllRoleBasicBy(
        @Parameter(name = "dto", description = "", required = true, in = ParameterIn.QUERY) RoleQueryDto dto
    );


    /**
     * GET /role
     *
     * @param dto  (required)
     * @return OK (status code 200)
     */
    @ResponseStatus(HttpStatus.OK)
    @HttpExchange(
        method = "GET",
        value = "/role",
        accept = { "*/*" }
    )
    Flux<RoleDto> findAllRoleBy(
        @Parameter(name = "dto", description = "", required = true, in = ParameterIn.QUERY) RoleQueryDto dto
    );


    /**
     * GET /role/{id}
     *
     * @param id  (required)
     * @return OK (status code 200)
     */
    @ResponseStatus(HttpStatus.OK)
    @HttpExchange(
        method = "GET",
        value = "/role/{id}",
        accept = { "*/*" }
    )
    Mono<RoleDto> findRoleById(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Long id
    );


    /**
     * PUT /role/{id}
     *
     * @param id  (required)
     * @param roleDto  (required)
     * @return OK (status code 200)
     */
    @ResponseStatus(HttpStatus.OK)
    @HttpExchange(
        method = "PUT",
        value = "/role/{id}",
        accept = { "application/json" },
        contentType = "application/json"
    )
    Mono<Void> updateRoleById(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Long id,
        @Parameter(name = "RoleDto", description = "", required = true) @RequestBody Mono<RoleDto> roleDto
    );

}
