/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.17.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.sct.system.client.api;

import com.sct.system.client.model.PageRequestDto;
import com.sct.system.client.model.PageResponseDtoSystemConfigBasicDto;
import com.sct.system.client.model.PageResponseDtoSystemConfigDto;
import com.sct.system.client.model.SystemConfigDto;
import com.sct.system.client.model.SystemConfigQueryDto;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.service.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;


@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-12-11T14:51:39.505559+08:00[Asia/Shanghai]", comments = "Generator version: 7.17.0")
public interface SystemConfigControllerApi {

    /**
     * GET /system-config/count
     *
     * @param queryDto  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "GET",
        value = "/system-config/count",
        accept = { "*/*" }
    )
    ResponseEntity<Long> countSystemConfigBy(
        @Parameter(name = "queryDto", description = "", required = true, in = ParameterIn.QUERY) SystemConfigQueryDto queryDto
    );


    /**
     * POST /system-config
     *
     * @param systemConfigDto  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "POST",
        value = "/system-config",
        accept = { "application/json" },
        contentType = "application/json"
    )
    ResponseEntity<Void> createSystemConfig(
        @Parameter(name = "SystemConfigDto", description = "", required = true) @RequestBody SystemConfigDto systemConfigDto
    );


    /**
     * DELETE /system-config/{id}
     *
     * @param id  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "DELETE",
        value = "/system-config/{id}",
        accept = { "application/json" }
    )
    ResponseEntity<Void> deleteSystemConfigById(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Long id
    );


    /**
     * GET /system-config/basic
     *
     * @param queryDto  (required)
     * @param pageRequestDto  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "GET",
        value = "/system-config/basic",
        accept = { "*/*" }
    )
    ResponseEntity<PageResponseDtoSystemConfigBasicDto> findAllSystemConfigBasicBy(
        @Parameter(name = "queryDto", description = "", required = true, in = ParameterIn.QUERY) SystemConfigQueryDto queryDto,
        @Parameter(name = "pageRequestDto", description = "", required = true, in = ParameterIn.QUERY) PageRequestDto pageRequestDto
    );


    /**
     * GET /system-config
     *
     * @param queryDto  (required)
     * @param pageRequestDto  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "GET",
        value = "/system-config",
        accept = { "*/*" }
    )
    ResponseEntity<PageResponseDtoSystemConfigDto> findAllSystemConfigBy(
        @Parameter(name = "queryDto", description = "", required = true, in = ParameterIn.QUERY) SystemConfigQueryDto queryDto,
        @Parameter(name = "pageRequestDto", description = "", required = true, in = ParameterIn.QUERY) PageRequestDto pageRequestDto
    );


    /**
     * GET /system-config/{id}
     *
     * @param id  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "GET",
        value = "/system-config/{id}",
        accept = { "*/*" }
    )
    ResponseEntity<SystemConfigDto> getSystemConfigById(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Long id
    );


    /**
     * PUT /system-config/{id}
     *
     * @param id  (required)
     * @param systemConfigDto  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "PUT",
        value = "/system-config/{id}",
        accept = { "application/json" },
        contentType = "application/json"
    )
    ResponseEntity<Void> updateSystemConfigById(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Long id,
        @Parameter(name = "SystemConfigDto", description = "", required = true) @RequestBody SystemConfigDto systemConfigDto
    );

}
