/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.17.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.sct.system.client.api;

import org.springframework.lang.Nullable;
import com.sct.system.client.model.PageResponseDtoTenantDto;
import com.sct.system.client.model.TenantBasicDto;
import com.sct.system.client.model.TenantDto;
import com.sct.system.client.model.TenantQueryDto;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.service.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;


@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-12-10T10:12:59.932325+08:00[Asia/Shanghai]", comments = "Generator version: 7.17.0")
public interface TenantControllerApi {

    /**
     * GET /tenant/count
     *
     * @param dto  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "GET",
        value = "/tenant/count",
        accept = { "*/*" }
    )
    ResponseEntity<Long> countAllTenantBy(
        @Parameter(name = "dto", description = "", required = true, in = ParameterIn.QUERY) TenantQueryDto dto
    );


    /**
     * POST /tenant
     *
     * @param tenantDto  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "POST",
        value = "/tenant",
        accept = { "application/json" },
        contentType = "application/json"
    )
    ResponseEntity<Void> createTenant(
        @Parameter(name = "TenantDto", description = "", required = true) @RequestBody TenantDto tenantDto
    );


    /**
     * DELETE /tenant/{id}
     *
     * @param id  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "DELETE",
        value = "/tenant/{id}",
        accept = { "application/json" }
    )
    ResponseEntity<Void> deleteTenantById(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Long id
    );


    /**
     * GET /tenant/basic
     *
     * @param dto  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "GET",
        value = "/tenant/basic",
        accept = { "*/*" }
    )
    ResponseEntity<List<TenantBasicDto>> findAllTenantBasicBy(
        @Parameter(name = "dto", description = "", required = true, in = ParameterIn.QUERY) TenantQueryDto dto
    );


    /**
     * GET /tenant
     *
     * @param dto  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "GET",
        value = "/tenant",
        accept = { "*/*" }
    )
    ResponseEntity<List<TenantDto>> findAllTenantBy(
        @Parameter(name = "dto", description = "", required = true, in = ParameterIn.QUERY) TenantQueryDto dto
    );


    /**
     * GET /tenant/page
     *
     * @param queryDto  (required)
     * @param pageNum  (optional, default to 1)
     * @param pageSize  (optional, default to 10)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "GET",
        value = "/tenant/page",
        accept = { "*/*" }
    )
    ResponseEntity<PageResponseDtoTenantDto> findAllTenantPageBy(
        @Parameter(name = "queryDto", description = "", required = true, in = ParameterIn.QUERY) TenantQueryDto queryDto,
        @Parameter(name = "pageNum", description = "", in = ParameterIn.QUERY) @RequestParam(value = "pageNum", required = false, defaultValue = "1") Integer pageNum,
        @Parameter(name = "pageSize", description = "", in = ParameterIn.QUERY) @RequestParam(value = "pageSize", required = false, defaultValue = "10") Integer pageSize
    );


    /**
     * GET /tenant/{id}
     *
     * @param id  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "GET",
        value = "/tenant/{id}",
        accept = { "*/*" }
    )
    ResponseEntity<TenantDto> findTenantById(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Long id
    );


    /**
     * PUT /tenant/{id}
     *
     * @param id  (required)
     * @param tenantDto  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "PUT",
        value = "/tenant/{id}",
        accept = { "application/json" },
        contentType = "application/json"
    )
    ResponseEntity<Void> updateTenantById(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Long id,
        @Parameter(name = "TenantDto", description = "", required = true) @RequestBody TenantDto tenantDto
    );

}
