/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.17.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.sct.system.client.api;

import com.sct.system.client.model.PageRequestDto;
import com.sct.system.client.model.PageResponseDtoUserBasicDto;
import com.sct.system.client.model.PageResponseDtoUserDto;
import com.sct.system.client.model.UserDto;
import com.sct.system.client.model.UserQueryDto;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.service.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;


@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-12-11T14:51:39.505559+08:00[Asia/Shanghai]", comments = "Generator version: 7.17.0")
public interface UserControllerApi {

    /**
     * GET /user/count
     *
     * @param queryDto  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "GET",
        value = "/user/count",
        accept = { "*/*" }
    )
    ResponseEntity<Long> countUserBy(
        @Parameter(name = "queryDto", description = "", required = true, in = ParameterIn.QUERY) UserQueryDto queryDto
    );


    /**
     * POST /user
     *
     * @param userDto  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "POST",
        value = "/user",
        accept = { "application/json" },
        contentType = "application/json"
    )
    ResponseEntity<Void> createUser(
        @Parameter(name = "UserDto", description = "", required = true) @RequestBody UserDto userDto
    );


    /**
     * DELETE /user/{id}
     *
     * @param id  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "DELETE",
        value = "/user/{id}",
        accept = { "application/json" }
    )
    ResponseEntity<Void> deleteUserById(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Long id
    );


    /**
     * GET /user/basic
     *
     * @param queryDto  (required)
     * @param pageRequestDto  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "GET",
        value = "/user/basic",
        accept = { "*/*" }
    )
    ResponseEntity<PageResponseDtoUserBasicDto> findAllUserBasicBy(
        @Parameter(name = "queryDto", description = "", required = true, in = ParameterIn.QUERY) UserQueryDto queryDto,
        @Parameter(name = "pageRequestDto", description = "", required = true, in = ParameterIn.QUERY) PageRequestDto pageRequestDto
    );


    /**
     * GET /user
     *
     * @param queryDto  (required)
     * @param pageRequestDto  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "GET",
        value = "/user",
        accept = { "*/*" }
    )
    ResponseEntity<PageResponseDtoUserDto> findAllUserBy(
        @Parameter(name = "queryDto", description = "", required = true, in = ParameterIn.QUERY) UserQueryDto queryDto,
        @Parameter(name = "pageRequestDto", description = "", required = true, in = ParameterIn.QUERY) PageRequestDto pageRequestDto
    );


    /**
     * GET /user/{id}
     *
     * @param id  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "GET",
        value = "/user/{id}",
        accept = { "*/*" }
    )
    ResponseEntity<UserDto> getUserById(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Long id
    );


    /**
     * PUT /user/{id}
     *
     * @param id  (required)
     * @param userDto  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "PUT",
        value = "/user/{id}",
        accept = { "application/json" },
        contentType = "application/json"
    )
    ResponseEntity<Void> updateUserById(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Long id,
        @Parameter(name = "UserDto", description = "", required = true) @RequestBody UserDto userDto
    );

}
