---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-cloud-service-template
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-cloud-service-template
  template:
    metadata:
      labels:
        app: spring-cloud-service-template
    spec:
      containers:
        - name: spring-cloud-service-template
          # sed -i 's#{IMAGE}#10.0.0.1:5000/$MAVEN_PROJECT_NAME:$MAVEN_PROJECT_VERSION-$BUILD_ID#' k8s.yaml
          image: "{IMAGE}"
          resources:
            limits:
              memory: "256Mi"
              cpu: "100m"
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: spring-cloud-service-template
spec:
  selector:
    app: spring-cloud-service-template
  ports:
    - port: 8080
      targetPort: 8080
