/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.17.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.sct.demo.client.api;

import com.sct.demo.client.model.DemoDto;
import com.sct.demo.client.model.DemoQueryDto;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.service.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;


@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-12-04T14:16:28.528767+08:00[Asia/Shanghai]", comments = "Generator version: 7.17.0")
public interface DemoControllerApi {

    /**
     * GET /demo/count
     *
     * @param dto  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "GET",
        value = "/demo/count",
        accept = { "*/*" }
    )
    ResponseEntity<Long> countAllDemoBy(
        @Parameter(name = "dto", description = "", required = true, in = ParameterIn.QUERY) DemoQueryDto dto
    );


    /**
     * POST /demo
     *
     * @param demoDto  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "POST",
        value = "/demo",
        accept = { "application/json" },
        contentType = "application/json"
    )
    ResponseEntity<Void> createDemo(
        @Parameter(name = "DemoDto", description = "", required = true) @RequestBody DemoDto demoDto
    );


    /**
     * DELETE /demo/{id}
     *
     * @param id  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "DELETE",
        value = "/demo/{id}",
        accept = { "application/json" }
    )
    ResponseEntity<Void> deleteDemoById(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Long id
    );


    /**
     * GET /demo
     *
     * @param dto  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "GET",
        value = "/demo",
        accept = { "*/*" }
    )
    ResponseEntity<List<DemoDto>> findAllDemoBy(
        @Parameter(name = "dto", description = "", required = true, in = ParameterIn.QUERY) DemoQueryDto dto
    );


    /**
     * GET /demo/{id}
     *
     * @param id  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "GET",
        value = "/demo/{id}",
        accept = { "*/*" }
    )
    ResponseEntity<DemoDto> findDemoById(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Long id
    );


    /**
     * PUT /demo/{id}
     *
     * @param id  (required)
     * @param demoDto  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "PUT",
        value = "/demo/{id}",
        accept = { "application/json" },
        contentType = "application/json"
    )
    ResponseEntity<Void> updateDemoById(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Long id,
        @Parameter(name = "DemoDto", description = "", required = true) @RequestBody DemoDto demoDto
    );

}
