/*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.17.0).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.sct.system.client.config;

import com.sct.system.client.api.DeptControllerApi;
import com.sct.system.client.api.DictItemControllerApi;
import com.sct.system.client.api.DictTypeControllerApi;
import com.sct.system.client.api.LoginLogControllerApi;
import com.sct.system.client.api.MenuControllerApi;
import com.sct.system.client.api.OperationLogControllerApi;
import com.sct.system.client.api.RoleControllerApi;
import com.sct.system.client.api.SystemConfigControllerApi;
import com.sct.system.client.api.TenantControllerApi;
import com.sct.system.client.api.UserControllerApi;

import org.springframework.context.annotation.Bean;
import org.springframework.web.reactive.function.client.WebClient;
import org.springframework.web.reactive.function.client.support.WebClientAdapter;
import org.springframework.web.service.invoker.HttpServiceProxyFactory;

public abstract class HttpInterfacesAbstractConfigurator {

    private final WebClient webClient;

    public HttpInterfacesAbstractConfigurator(final WebClient webClient) {
        this.webClient = webClient;
    }

    @Bean(name = "com.sct.system.client.config.HttpInterfacesAbstractConfigurator.deptController")
    DeptControllerApi deptControllerHttpProxy() {
        HttpServiceProxyFactory factory = HttpServiceProxyFactory.builderFor(WebClientAdapter.create(webClient)).build();
        return factory.createClient(DeptControllerApi.class);
    }

    @Bean(name = "com.sct.system.client.config.HttpInterfacesAbstractConfigurator.dictItemController")
    DictItemControllerApi dictItemControllerHttpProxy() {
        HttpServiceProxyFactory factory = HttpServiceProxyFactory.builderFor(WebClientAdapter.create(webClient)).build();
        return factory.createClient(DictItemControllerApi.class);
    }

    @Bean(name = "com.sct.system.client.config.HttpInterfacesAbstractConfigurator.dictTypeController")
    DictTypeControllerApi dictTypeControllerHttpProxy() {
        HttpServiceProxyFactory factory = HttpServiceProxyFactory.builderFor(WebClientAdapter.create(webClient)).build();
        return factory.createClient(DictTypeControllerApi.class);
    }

    @Bean(name = "com.sct.system.client.config.HttpInterfacesAbstractConfigurator.loginLogController")
    LoginLogControllerApi loginLogControllerHttpProxy() {
        HttpServiceProxyFactory factory = HttpServiceProxyFactory.builderFor(WebClientAdapter.create(webClient)).build();
        return factory.createClient(LoginLogControllerApi.class);
    }

    @Bean(name = "com.sct.system.client.config.HttpInterfacesAbstractConfigurator.menuController")
    MenuControllerApi menuControllerHttpProxy() {
        HttpServiceProxyFactory factory = HttpServiceProxyFactory.builderFor(WebClientAdapter.create(webClient)).build();
        return factory.createClient(MenuControllerApi.class);
    }

    @Bean(name = "com.sct.system.client.config.HttpInterfacesAbstractConfigurator.operationLogController")
    OperationLogControllerApi operationLogControllerHttpProxy() {
        HttpServiceProxyFactory factory = HttpServiceProxyFactory.builderFor(WebClientAdapter.create(webClient)).build();
        return factory.createClient(OperationLogControllerApi.class);
    }

    @Bean(name = "com.sct.system.client.config.HttpInterfacesAbstractConfigurator.roleController")
    RoleControllerApi roleControllerHttpProxy() {
        HttpServiceProxyFactory factory = HttpServiceProxyFactory.builderFor(WebClientAdapter.create(webClient)).build();
        return factory.createClient(RoleControllerApi.class);
    }

    @Bean(name = "com.sct.system.client.config.HttpInterfacesAbstractConfigurator.systemConfigController")
    SystemConfigControllerApi systemConfigControllerHttpProxy() {
        HttpServiceProxyFactory factory = HttpServiceProxyFactory.builderFor(WebClientAdapter.create(webClient)).build();
        return factory.createClient(SystemConfigControllerApi.class);
    }

    @Bean(name = "com.sct.system.client.config.HttpInterfacesAbstractConfigurator.tenantController")
    TenantControllerApi tenantControllerHttpProxy() {
        HttpServiceProxyFactory factory = HttpServiceProxyFactory.builderFor(WebClientAdapter.create(webClient)).build();
        return factory.createClient(TenantControllerApi.class);
    }

    @Bean(name = "com.sct.system.client.config.HttpInterfacesAbstractConfigurator.userController")
    UserControllerApi userControllerHttpProxy() {
        HttpServiceProxyFactory factory = HttpServiceProxyFactory.builderFor(WebClientAdapter.create(webClient)).build();
        return factory.createClient(UserControllerApi.class);
    }


}
